name: sync version
on:
  repository_dispatch:
    types: [sync-version]

jobs:
  tag-release:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: set up git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: update version in CMakeLists.txt
        run: |
          VERSION=${{ github.event.client_payload.version }}
          echo "new version: $VERSION"
          
          # update project line (e.g., set(PROJECT_VERSION 0.1.0))
          sed -i "s/^project(\(.*\) VERSION .*)/project(\1 VERSION $VERSION})/" CMakeLists.txt 
          
          # commit change
          git add CMakeLists.txt
          git commit -m "chore: update version to $VERSION"
          
      - name: push commit and tag
        run: |
          VERSION=${{ github.event.client_payload.version }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag $VERSION
          git push origin $VERSION
